config/routes.rb
Rails.application.routes.draw do
  get 'artworks_in_space/create'
  get 'artworks_in_space/destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces do
    resources :artworks, only: [:create, :update]

    get 'vr', to: 'spaces#vr'
  end

  resources :user_space_templates, only: [:create, :destroy, :edit, :update]

  resources :artworks, only: :destroy
  resources :users, only: [:show, :index]

end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  belongs_to :public_space_template, optional: true
  belongs_to :user_space_template, optional: true

  before_create :clean_template_choice

  # has_many :artworks, dependent: :destroy
  has_many :artwork_in_spaces, dependent: :destroy
  has_one_attached :photo, service: :s3_free
  has_one_attached :fast_photo, service: :s3_paid

  PUBLIC_OR_CUSTOM_OPTIONS = [[:public, "Public"], [:custom, "Custom"]]

  attr_accessor :public_or_custom

  validates :name, presence: true
  validates :photo, presence: true, if: -> { user.subscription == 'free' }
  validates :fast_photo, presence: true, if: -> { user.subscription == 'paid' }
  validates :public_space_template, presence: { message: "You must choose a gallery template from the left" }, if: -> { public_or_custom != 'Custom' } #public_or_custom set to NOT custom, so that it can also catch values that are neither custom nor public i.e. if somebody tinkers with what is sent from the frontend
  validates :user_space_template, presence: { message: "You must choose a gallery template from the left" }, if: -> { public_or_custom != 'Public' } #public_or_custom set to NOT public, so that it can also catch values that are neither custom nor public i.e. if somebody tinkers with what is sent from the frontend

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

  def attachment
    if :photo
      return :photo
    elsif :fast_photo
      return :fast_photo
    end
  end

  def clean_template_choice
    if public_or_custom == 'Public'
      self.user_space_template_id = nil
    else
      self.public_space_template_id = nil
    end
  end

  def getSpaceModel
    if self.user.subscription == "free"
      return "https://musegallerytemplatesfree.s3.eu-west-2.amazonaws.com/#{self.public_space_template.model_url}"
    elsif self.user.subscription == "paid"
      return "https://d270od7aj4kefu.cloudfront.net/#{self.public_space_template.model_url}"
    end
  end

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :redirect_to_home_if_not_logged_in, only: [:index, :vr]
  before_action :set_space, only: [:show, :edit, :destoy, :update]

  def index
    if params[:search] == "" || params[:search].nil?
      @spaces = Space.where.not(user_id: 0)
    else
      @spaces = Space.search(params[:search])
    # raise
    end
    # @users = User.all
  end

  def show
    @artwork = Artwork.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @space = Space.new
    @user_space_template = UserSpaceTemplate.new
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("spaces/*.png")
    end
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user

    if @space.save
      redirect_to space_path(@space)
    else
      @user_space_template = UserSpaceTemplate.new
      render :new
    end
  end

  def edit
  end

  def destroy
    @user = @space.user
    @space.destroy
    redirect_to user_path(@user)
  end

  def update
    # @space.photo.attach(params[:photo])
    if @space.update!(space_params)
      redirect_to space_path(@space)
    else
      render 'spaces/show'
    end
  end


  def vr
    @space = Space.find(params[:space_id])
  end

  private

  def set_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:name, :description, :user_id, :fast_photo, :photo, :public_space_template_id, :user_space_template_id, :public_or_custom)
  end
end

app/views/spaces/_add_artwork.html.erb
<!-- <div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>
 -->


<!-- , remote: true  -->
<%= simple_form_for [@space, @artwork] do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, input_html: { class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "The name of your artwork" %>
  <%= f.input :description, input_html: { class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "Describe your artwork", placeholder: 'Talk about materials, size-dimensions, historical context...' %>
  <%=  f.label :artwork_type, label: "What type of artwork are you uploading?", required: true %>
  <div class="d-flex justify-content-around pb-3">
    <%= f.input_field :artwork_type, as: :radio_buttons, collection: Artwork::OPTIONS, required: true, checked: "Image", item_wrapper_class: "artworkTypeSelection" %>
  </div>
  <%#= f.label :photo, label: "Choose your artwork", label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" } %>
  <%#= cl_upload_tag(@artwork.id) %>
  <% if current_user.subscription == "paid" %>
    <%= f.input :fast_photo, as: :file, label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" }, label: "Choose your artwork" %>
  <% else %>
    <%= f.input :photo, as: :file, label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" }, label: "Choose your artwork" %>
  <% end %>
  <%= f.submit "Add artwork", class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px;" %>
<% end %>

app/views/spaces/_add_new_user_template.html.erb
<div>
  <%= simple_form_for @user_space_template do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, input_html: { class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label: "Give your template a name" %>
    <%= f.input :photo, as: :file, label: "Pick a cover photo for your gallery" %>
    <%= f.input :model, as: :file, label: "Upload 3D model - we currently only accept .glb", input_html: { accept: '.glb' } %>
    <%= f.submit "Upload custom template", class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px;" %>
  <% end %>

</div>

app/views/spaces/_edit_artwork.html.erb
<%= simple_form_for [@space, artwork], method: :patch, url: space_artwork_path(@space,artwork) do |f| %>
  <%= f.input :name, input_html: { value: artwork.name, class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "The name of your artwork" %>
  <%= f.input :description, input_html: { value: artwork.description, class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "Describe your artwork", placeholder: 'Talk about materials, size-dimensions, historical context...' %>
  <%=  f.label :artwork_type, label: "What type of artwork are you uploading?", required: true %>
  <div class="d-flex justify-content-around pb-3">
    <%= f.input_field :artwork_type, as: :radio_buttons, collection: Artwork::OPTIONS, required: true, checked: artwork.artwork_type, item_wrapper_class: "artworkTypeSelection" %>
  </div>
  <%#= f.label :photo, label: "Choose your artwork", label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" } %>
  <%#= cl_upload_tag(@artwork.id) %>
  <%= f.input :photo, as: :file, label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" }, label: "Choose your artwork" %>
  <div style="display:flex; justify-content: space-between;">
    <%= link_to "Delete", artwork_path(artwork), class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px;", data: { confirm: 'Are you sure?' }, method: :delete %>
    <%= f.submit "Update artwork", class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px;" %>
  </div>
  <% end %>

app/views/spaces/_edit_space.html.erb
<%= simple_form_for @space, method: :patch, url: space_path(@space) do |f| %>
  <%= f.input :name, input_html: { value: @space.name, class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "The name of your gallery" %>
  <%= f.input :description, input_html: { value: @space.description, class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "Gallery description" %>
  <%= f.file_field :photo, label_html: {style: "color: $text; font-weight: 600; font-size: 16px;" }, label: "Choose a new cover photo" %>
  <%= f.submit "Update gallery details", class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px;" %>
<% end %>

app/views/spaces/index.html.erb
<!-- show all the spaces -->


<% @title="Musei - Gallery index page" %>

<div class="page-container">
  <div class="spaces-index-heading">
    <h1>GALLERIES</h1>
  </div>

  <div class="spaces-index-subtitle">
    <% if @spaces.count == 0 %>
      <h2> No galleries to browse on Muse </h2>
    <% elsif @spaces.count == 1 %>
      <h2> Browse 1 gallery on Muse </h2>
    <% else %>
      <h2> Browse the <%=@spaces.count%> galleries on Muse </h2>
    <% end %>
  </div>


  <div  class="container show-page-container" >
    <div class="row">
      <% @spaces.each do |space| %>
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6 d-flex justify-content-center bottom-buffer">
          <%= (render partial: 'shared/card', locals: { space: space }) %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/spaces/new.html.erb
<% @title="Musei - Create new gallery page" %>

<%= simple_form_for @space, html: {class:""}, defaults: {label: false} do |f| %>
  <div class="container p-0 page-size" style="margin:none;">
    <div class="row page-size">

      <div class="col-md-12 col-lg-6 p-0">

        <div class="h-100 d-flex flex-column align-items-center justify-content-center">
          <section class="w-100">
            <p>Choose a template for your gallery</p>

            <div class="row">
              <div class="col-3 ">
                <div class="nav flex-column nav-pills nav-fill h-100" id="v-pills-tab" role="tablist" aria-orientation="vertical">

                  <a class="pill-picker-toggle nav-link d-flex align-items-center justify-content-center <%= @space.public_or_custom.nil? || @space.public_or_custom == "Public" ? "active" : "" %>" id="v-pills-public-tab" data-input-id="public" data-toggle="pill" href="#v-pills-public" role="tab" aria-controls="v-pills-public" aria-selected=<%= @space.public_or_custom.nil? || @space.public_or_custom == "Public" ? true : false %>> Public </a>
                  <a class="pill-picker-toggle nav-link d-flex align-items-center justify-content-center <%= @space.public_or_custom == "Custom" ? "active" : "" %>" id="v-pills-custom-tab" data-input-id="custom" data-toggle="pill" href="#v-pills-custom" role="tab" aria-controls="v-pills-custom" aria-selected=<%= @space.public_or_custom == "Custom" ? true : false %>>My spaces</a>
                </div>
                <%#= raise "" %>
                <%= f.input :public_or_custom,
                    as: :radio_buttons,
                    collection: Space::PUBLIC_OR_CUSTOM_OPTIONS,
                    checked: "public",
                    label: "",
                    legend_tag: false,
                    item_label_class: "d-none",
                    input_html: {class: "d-none"}
                    %>
              </div>
              <div class="col-9">
                <div class="tab-content" id="v-pills-tabContent">
                  <div class="tab-pane fade show <%= @space.public_or_custom.nil? || @space.public_or_custom == "Public" ? "active" : "" %>" id="v-pills-public" role="tabpanel" aria-labelledby="v-pills-public-tab">
                    <!-- Slider main container -->
                    <div class="swiper-container">
                      <!-- Additional required wrapper -->
                      <div class="swiper-wrapper">
                        <!-- Slides -->
                        <%= f.collection_radio_buttons(
                             :public_space_template_id,
                             PublicSpaceTemplate.get_all_templates,
                             :first, :last,  :item_wrapper_class => 'swiper-slide') do |space| %>
                                <div class="space-name-overlay"><%= space.text[1] %></div>
                                <%= space.label(:class => "h-100 w-100"){(render partial: 'shared/space_modal_card', locals: { image: space.text[0], space: space }) } %>
                        <% end %>
                      </div>
                      <!-- If we need pagination -->
                      <div class="swiper-pagination"></div>

                      <!-- If we need navigation buttons -->
                      <div class="swiper-button-prev"></div>
                      <div class="swiper-button-next"></div>
                    </div>
                  </div>

                  <div class="tab-pane fade <%= @space.public_or_custom == "Custom" ? "active" : "" %>" id="v-pills-custom" role="tabpanel" aria-labelledby="v-pills-custom-tab">
                    <!-- Slider main container -->
                    <% if current_user.user_space_templates.any? %>
                      <div class="swiper-container-2">
                        <!-- Additional required wrapper -->
                        <div class="swiper-wrapper">
                          <!-- Slides -->
                            <%= f.collection_radio_buttons(
                                 :user_space_template_id,
                                 current_user.get_all_user_templates,
                                 :first, :last,  :item_wrapper_class => 'swiper-slide custom-slides') do |space| %>
                                  <div class="space-name-overlay"><%= space.text[1] %></div>
                                  <%= space.label(:class => "h-100 w-100"){(render partial: 'shared/space_modal_card', locals: { image: space.text[0], space: space }) } %>
                            <% end %>
                        </div>
                        <%# raise "" %>
                        <!-- If we need pagination -->
                        <div class="swiper-pagination"></div>

                        <!-- If we need navigation buttons -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>

                      </div>
                    <% else %>
                      <div class="swiper-container d-flex align-items-center justify-content-center">
                        <p>You haven't added any custom templates yet</p>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

          </section>

          <section class="mt-4">
            <p>Add a new template to your library</p>
            <div class="w-100">
              <%= link_to "#", class: "text-decoration-none ", data: {toggle: "modal", target: "#addNewTemplateModal", backdrop: "true"} do %>
                <div class="mx-auto template-picker-size add-new-space-template d-flex align-items-center justify-content-center">
                  <i class="fas fa-plus"></i>
                </div>
              <% end %>
            </div>
          </section>

       </div>



        <!-- <div style="width: 100%; height:100%;">
          <div id="carouselExampleControls" class="carousel slide" data-interval="false" style="width: 100%; height:100%;">
            <div class="carousel-inner" style="width: 100%; height:100%;">

                <%#= f.collection_radio_buttons(
                    :public_space_template_id,
                    PublicSpaceTemplate.get_all_templates,
                    :first, :last,  :item_wrapper_class => 'carousel-item w-100 h-100') do |space| %>

                <%#= space.label(:class => "h-100 w-100"){(render partial: 'shared/space_modal_card', locals: { image: space.text, space: space }) } %>
              <%# end %>
            </div>

            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>

            <div id="carouselTextHolder">
            </div>
            <h2 id="carouselText">Click an image above to pick your gallery</h2>
          </div>
        </div> -->
      </div>

      <div class="col-md-12 col-lg-6 p-0">
        <!-- <div> -->
          <div class="d-flex flex-column" style="height:100%; width: 80%; margin: auto;">

            <div style="height:35%;">
              <div class="h-100 d-flex flex-column justify-content-end">
                <% if @space.errors.any? %>
                  <div id="error_explanation">
                    <ul style="list-style: none; color: red; padding-left: 0;">
                      <li style="padding-bottom: 24px;">
                        <% error = @space.errors.full_messages.last.split(" ")%>
                        <% error.shift %>
                        <%= error.join(" ") %>
                      </li>
                    </ul>
                  </div>
                <% end %>
              </div>
            </div>

            <div style="height:25%; width: 100%;">
                <%= f.input :name, input_html: { class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 32px;" }, label: "Name your gallery" %>
                <%= f.input :description, input_html: { class: "transparent simpleFormInput", style: "border: 0; border-bottom: 1px dotted #333333;" }, label_html: {style: "color: $text; font-weight: 600; font-size: 32px;" }, label: "Gallery description" %>
                <% if current_user.subscription == "free" %>
                  <%= f.file_field :photo, required: true, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "Upload a cover photo for your gallery" %>
                <% else %>
                  <%= f.file_field :fast_photo, required: true, label_html: {style: "color: $text; font-weight: 600; font-size: 24px;" }, label: "Upload a cover photo for your gallery" %>
                <% end %>
                <%= f.submit "Add art to your gallery>>", class: "transparent submitButton", style: "border:0; float: right; margin-top: 24px; margin-bottom: 48px;" %>

            </div>
          </div>
        </div>
      <!-- </div> -->
    </div>
  </div>
<% end %>


<div class="modal fade" id="addNewTemplateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgba(255,255,255,0.93); border-radius: 8px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add your own space template</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-4">
        <%= render "add_new_user_template" %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<% @title="Musei - Gallery assets page" %>

<% modelViewerActive = false %>

<div class="page-container">

  <div class="d-flex m-auto w-100 justify-content-center gallery-show-height">
         <div class="d-flex justify-content-center align-items-center h-100">
        <%= (render partial: 'shared/space_show_cover_photo', locals: { space: @space }) %>
      </div>

      <div class="gallery-show-header-margin">
        <div class="d-flex flex-column align-items-left justify-content-between gallery-show-header-padding" style="width:100%;height:100%;border-left:1px solid grey;">

          <div class="d-flex">
            <h1 class="gallery-show-title m-0"><%= @space.name %></h1>

            <div class="h-100 d-flex flex-column justify-content-end pl-3 edit-gallery-padding">
              <button type="button" class="edit-gallery-info-button transparent " data-toggle="modal" data-target="#editSpaceModal" data-backdrop="true">EDIT</button>
            </div>
          </div>

          <div >
            <h2 class="gallery-show-bio"><%= @space.description %></h2>
          </div>

           <div>
            <%= link_to "LAUNCH ROOM", space_vr_path(@space), class:"launch-room-button", data: {turbolinks: false} %>
          </div>

        </div>
      </div>
  </div>


  <div class="container-fluid show-page-container">
    <div class="w-100 d-flex justify-content-center">
      <span style="border-top: 1px solid grey; width: 80%;"></span>
    </div>

    <div class="container" style="margin-top: 32px;">
      <button type="button" class="transparent addArtButton" style="border:0;" data-toggle="modal" data-target="#addArtworkModal">+ Add artwork +</button>
    </div>

    <div class="row">
      <% @space.artwork_in_spaces.each do |artwork| %>
        <% modelViewerActive = true if artwork.artwork_type == "3D Model" %>
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6 d-flex justify-content-center bottom-buffer">
          <%= (render partial: 'shared/space_show_artwork_card', locals: { artwork: artwork }) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="addArtworkModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgba(255,255,255,0.93); border-radius: 8px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Upload an artwork</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-4">
        <%= render "add_artwork" %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editSpaceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgba(255,255,255,0.93); border-radius: 8px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit gallery details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-4">
        <%= render "edit_space" %>
      </div>
    </div>
  </div>
</div>


<!-- Some scripts which handle showing 3d asset on page - will be good to move later when showing 3d assets on other pages - such as within
a JS file that loads scripts dependent on page - akin to how you currently have your index.js set up -->
<% if modelViewerActive %>
  <!-- Loads model-viewer for modern browsers -->
  <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
  <!-- Loads model-viewer for older browsers -->
  <script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>
<% end %>