config/routes.rb
Rails.application.routes.draw do
  get 'artworks_in_space/create'
  get 'artworks_in_space/destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces do
    resources :artworks, only: [:create, :update]

    get 'vr', to: 'spaces#vr'
  end

  resources :user_space_templates, only: [:create, :destroy, :edit, :update]

  resources :artworks, only: :destroy
  resources :users, only: [:show, :index]

end

app/views/shared/_artwork_card.html.erb
<div class="main" >
    <% card_image = image_path artwork.photo.service_url %>

    <div class="card" style="width: 500px; height:500px; background-image: url(<%= card_image %>)">
      <div class= "spaces-card-text d-flex justify-content-center align-items-center h-100 w-100">
        <h4 class= "name_of_space"><%=artwork.name%></h4>
      </div>
    </div>
</div>

app/views/shared/_card.html.erb
<div class="main" >
  <% if space.user == current_user %>
    <% card_path = space_path(space) %>
  <% else %>
    <% card_path = space_vr_path(space) %>
  <% end %>
    <%= link_to card_path do %>
      <% if space.photo.attached? %>
        <% card_image = image_path space.photo.service_url %>
      <% else %>
        <% card_image = "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1418&q=80" %>
      <% end %>

      <div class="card card-size" style="background-image: url(<%= card_image %>)">
        <div class= "spaces-card-text d-flex justify-content-center align-items-center h-100 w-100">
          <h4 class= "name_of_space"> View <%=space.name%></h4>
        </div>
      </div>
    <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_login_modal.html.erb
<div id="login-modal-view" style="">
  <div class="container">

    <h2 class="login-title-label" style="padding-bottom: 24px;">Log in</h2>

    <div>
      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true, html: {id: "newUserLogin"}) do |f| %>
        <%#= render 'shared/flashes', :object => f.object %>

        <div class="form-inputs">
          <%= f.input :email,
              label: "EMAIL",
              required: false,
              autofocus: true,
              placeholder: "type email here...",
              input_html: { autocomplete: "email", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserLoginEmail" },
              label_html: { class: "modal-label" } %>
          <%= f.input :password,
              label: "PASSWORD",
              required: false,
              placeholder: "type password here...",
              input_html: { autocomplete: "current-password", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserLoginPassword" },
              label_html: { class: "modal-label" } %>
          <%= f.input :remember_me, label: "Remember me", label_html: { class: "modal-label" }, as: :boolean if devise_mapping.rememberable? %>
        </div>

        <div class="form-actions">
          <div class="d-flex justify-content-end">
            <div class="errors modal-label" style="color: red;"></div>
            <%= f.submit "SUBMIT", inner_text: "SUBMIT", style: "float: right; background: none; border: 0;", class: "modal-label login-submit" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="container" style="display: none;">
        <div class="d-flex flex-column align-items-center" style="margin-top: 24px; width: 100%;">
          <%- if devise_mapping.omniauthable? %>
              <div>
                <h3 class="modal-label border-top border-dark" style="margin-bottom: 36px; text-align: center; padding-top: 16px;">Or login with socials:</h2>
              </div>

              <div class="d-flex justify-content-center pb-5 border-bottom border-dark">
                <%- resource_class.omniauth_providers.each do |provider| %>
                  <% if provider == :facebook %>
                    <%= link_to "", omniauth_authorize_path(resource_name, provider), class: "fab fa-facebook-f fa-3x fa-logo" %>
                    <div style="width:144px;"></div>
                  <% elsif provider == :github %>
                    <%= link_to "", omniauth_authorize_path(resource_name, provider), class: "fab fa-github fa-3x fa-logo" %>
                  <% end %>
                <% end %>
              </div>
          <% end %>
        </div>
    </div>

    <div class="d-flex justify-content-between pt-2" >
      <%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <%#= link_to "Don't have an account?", new_registration_path(resource_name), class: "modal-label login-submit pt-3" %>
      <%# end %>
      <button class="modal-label login-submit transparent pt-3 remove-glow" id="switch-to-signup" style="height: 20px; border: 0;" >Don't have an account?</button>

      <button class="modal-label login-submit transparent pt-3 remove-glow" id="switch-to-password-reset" style="height: 20px; border: 0;" >Forgot your password?</button>

      <%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <%#= link_to "Forgot your password?", new_password_path(resource_name), class: "modal-label login-submit pt-3 remove-glow" %>
      <%# end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon align-items-center px-0 py-4 <%= params[:action] == "vr" ? "white-background z-index" : "transparent" %>">

  <% searchAction = "" %>
  <% if params[:controller] == 'spaces' %>
    <% searchAction = "/spaces" %>
  <% elsif params[:controller] == 'users' && params[:action] == 'index' %>
    <% searchAction = "/users" %>
  <% elsif params[:controller] == 'users' && params[:action] == 'show' %>
    <% searchAction = "/users/#{user.id}" %>
  <% end %>

  <%= link_to "/", class: "navbar-brand navbar-logo-margin" do %>
    <h1 class="logo">MUSEI</h1>
    <%# if (params[:controller] == 'spaces' && params[:action] == 'new') %>
      <!-- <div class="navbarUnderContent" style=""></div> -->
    <%# end %>
  <% end %>

  <div class="d-flex">
    <%  if (params[:controller] == 'users' && params[:action] == 'show') %>
      <span style="width:100%; max-width: 150px;"></span>
      <div class="mr-auto medium-width navbar-collapse-search-custom" id="navbar-search" style="margin:auto;">
        <form action="<%=searchAction%>" method="get" class="form-inline d-flex justify-content-center md-form form-sm active-purple-2 mt-2">
          <input class="form-control form-control-sm mr-3 w-75 search-bar" style="border:0px; border-bottom: 1px solid #CCC9A1; border-radius: 0px; background-color: transparent;" type="text" placeholder="Search for a gallery" name="search" aria-label="Search">
          <button type="submit" class="border-0" style="background-color: transparent;"><i class="fas fa-search" aria-hidden="true"></i></button>
        </form>
      </div>
      <span style="width:100%; max-width: 250px;"></span>
    <% end %>


    <% if (params[:controller] == 'spaces' || params[:controller] == 'users') && params[:action] == 'index' %>

      <!-- <span style="width:100%; max-width: 250px;"></span> -->
      <div class="mr-auto medium-width navbar-collapse-search-custom" id="navbar-search">

        <form action="<%=searchAction%>" method="get" class="form-inline d-flex justify-content-center md-form form-sm active-purple-2 mt-2">
          <input class="form-control form-control-sm mr-3 w-75 search-bar" style="border:0px; border-bottom: 1px solid #CCC9A1; border-radius: 0px; background-color: transparent;" type="text" placeholder="Search" name="search" aria-label="Search">
          <button type="submit" class="border-0" style="background-color: transparent;"><i class="fas fa-search" aria-hidden="true"></i></button>
        </form>
      </div>
      <!-- <span style="width:100%; max-width: 170px;"></span> -->

      <div class="" id="menu">
        <%= link_to 'Galleries', spaces_path, class: "menu-item #{'active' if params[:controller] == 'spaces'} navbar-collapse-links-custom" %>
        <%= link_to 'Artists', users_path, class: "menu-item #{'active' if params[:controller] == 'users'} navbar-collapse-links-custom"  %>
      </div>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-right: 45px;">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <button class="dropdown-toggle border-0 transparent" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bars fa-2x"></i></button>
            <div class="dropdown-menu dropdown-menu-right border-0 dropdown-width" style="text-align: right; margin-right: -24px;" aria-labelledby="navbarDropdown">

              <% if ((params[:controller] == 'spaces' || params[:controller] == 'users') && params[:action] == 'index') || (params[:controller] == 'users' && params[:action] == 'show')  %>
                <div class="navbar-collapse-search-dropdown-custom" id="navbar-search" style="">
                  <form action="<%=searchAction%>" method="get" class="form-inline d-flex justify-content-center md-form form-sm active-purple-2 mt-2">
                    <input class="form-control form-control-sm mr-3 w-75 search-bar" style="border:0px; border-bottom: 1px solid #CCC9A1; border-radius: 0px; background-color: transparent;" type="text" placeholder="Search" name="search" aria-label="Search">
                    <button type="submit" class="border-0" style="background-color: transparent;"><i class="fas fa-search" aria-hidden="true"></i></button>
                  </form>
                </div>
              <% end %>

              <%if params[:controller] == 'users' && params[:action] == 'index' %>
                <%= link_to 'Galleries', spaces_path, class: "dropdown-item navbar-collapse-links-dropdown-custom" %>
                <div class="dropdown-divider navbar-collapse-links-dropdown-custom divider-color-width"></div>
              <% elsif params[:controller] == 'spaces' && params[:action] == 'index' %>
                <%= link_to 'Artists', users_path, class: "dropdown-item navbar-collapse-links-dropdown-custom"  %>
                <div class="dropdown-divider navbar-collapse-links-dropdown-custom divider-color-width"></div>
              <% end %>

              <%= link_to "Explore", spaces_path, class: "dropdown-item mt-2" %>
              <% if user_signed_in? %>
                <%= link_to "My spaces", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Create new space", new_space_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                <!-- <button type="button" class="transparent addArtButton" style="border:0;" data-toggle="modal" data-target="#artworkModal"> -->
                <%= link_to "Login", "#", id: "login-modal-trigger" , class: "dropdown-item", data: {toggle: "modal", target: "#loginModal", backdrop: false} %>

              <% end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>


<div class="modal login-modal-backdrop" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="login-modal-dialog" style="margin-top: 2vh; margin-bottom: 2vh;" role="document">
    <div class="modal-content modal-blur-in" id="login-modal-content" style="background: transparent; border: 0; margin-top: 32px;">
      <div class="d-flex justify-content-end">
        <button id="close-login-modal" class="login-close remove-glow" style="border:none; width:10%; text-align:center; background: transparent;">X</button>
      </div>
      <div class="modal-body" style="padding-top: 0; padding-bottom: 0;">
        <%#=  render file: 'devise/sessions/new' %>
        <%#=  render file: 'devise/registrations/new' %>

        <%= render partial: "shared/login_modal" %>
        <%= render partial: "shared/signup_modal" %>
        <%= render partial: "shared/password_modal" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_users_galleries_index.html.erb
<div class="navbar navbar-expand-xl navbar-light navbar-lewagon align-items-center transparent px-0 py-4">
  <%= link_to "/", class: "navbar-brand", style: "margin-left: 96px;" do %>
    <h1 class="logo">MUSE</h1>
  <% end %>

  <div class="mr-auto medium-width" id="navbar-search" class="artist-index-search" style="margin-left: 250px;">
    <form action="/spaces" method="get" class="form-inline d-flex justify-content-center md-form form-sm active-purple-2 mt-2">
      <input class="form-control form-control-sm mr-3 w-75 search-bar" style="border:0px; border-bottom: 1px solid #CCC9A1; border-radius: 0px; background-color: transparent;" type="text" placeholder="Search" name="search" aria-label="Search">
      <button type="submit" class="border-0" style="background-color: transparent;"><i class="fas fa-search" aria-hidden="true"></i></button>
    </form>
  </div>

  <div id="menu">
    <%= link_to 'Galleries', spaces_path, class: "menu-item #{'active' if params[:controller] == 'spaces'}" %>
    <%= link_to 'Artists', users_path, class: "menu-item #{'active' if params[:controller] == 'users'}"  %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-right: 45px;">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <i class="fal fa-bars fa-2x dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu dropdown-menu-right transparent border-0" style="text-align: right; margin-right: -24px;" aria-labelledby="navbarDropdown">
            <%= link_to "Home", spaces_path, class: "dropdown-item" %>
            <% if user_signed_in? %>
              <%= link_to "My spaces", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Create new space", new_space_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
    </ul>
  </div>
</div>

app/views/shared/_password_modal.html.erb
<div id="password-modal-view" style="display: none;">
  <div class="container">

    <h2 class="login-title-label" style="px;">Reset your password</h2>
    <h3 class="modal-label" style="padding-bottom: 24px;">Enter the email associated with your account, and we will send you a link to reset your password</h3>
    <div>
      <%= simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, id: "forgottenPassword" }, remote: true) do |f| %>
        <%#= render 'shared/flashes', :object => f.object %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email,
              label: "EMAIL",
              required: true,
              autofocus: true,
              placeholder: "type email here...",
              input_html: { autocomplete: "email", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "resetPasswordEmail" },
              label_html: { class: "modal-label" } %>
        </div>
        <div class="form-actions">
          <div class="d-flex justify-content-end">
            <div class="password-reset-errors modal-label" style="color: red;"></div>
            <%= f.submit "SUBMIT", inner_text: "Send me reset password instructions", style: "float: right; background: none; border: 0;", class: "modal-label login-submit" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-between pt-2" >
      <%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <%#= link_to "Don't have an account?", new_registration_path(resource_name), class: "modal-label login-submit pt-3" %>
      <%# end %>
      <!-- <button class="modal-label login-submit transparent pt-3 remove-glow" id="switch-to-signup" style="height: 20px; border: 0;" >Sign up</button> -->
      <button class="modal-label login-submit transparent pt-3 remove-glow" id="back-from-password" style="height: 20px; border: 0;" >Back to log in</button>


      <%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
        <%#= link_to "Forgot your password?", new_password_path(resource_name), class: "modal-label login-submit pt-3 remove-glow" %>
      <%# end %>
    </div>
  </div>
</div>

app/views/shared/_signup_modal.html.erb
<div id="signup-modal-view" style="display:none;">

  <div class="container d-flex justify-content-between">
    <h2 class="login-title-label" style="padding: 0 0 24px 0;">Sign up </h2>

    <%#- if controller_name != 'sessions' %>
      <button class="modal-label login-submit transparent remove-glow" id="switch-to-login" style="height: 20px; border: 0;" >Already have an account?</button>
    <%# end %>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-12 pr-5">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true, html: {id: "newUserSignup"}) do |f| %>
          <!-- <div id="signupErrorsTest"></div> -->
          <div class="form-inputs">
            <%= f.input :email,
                        label: "EMAIL",
                        required: true,
                        autofocus: true,
                        placeholder: "type email here...",
                        input_html: { autocomplete: "email", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserSignupEmail"  },
                        label_html: { class: "modal-label" } %>
          </div>
        </div>
        <div class="col-lg-6 col-sm-12 pr-5">
          <div class="form-inputs">
            <%= f.input :username,
                        label: "USERNAME",
                        required: true,
                        placeholder: "create a username...",
                        input_html: { class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserSignupUsername" },
                        label_html: { class: "modal-label" } %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 col-sm-12 pr-5">
          <div class="form-inputs">
            <%= f.input :password,
                        label: "PASSWORD",
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        placeholder: "type password here...",
                        input_html: { autocomplete: "new-password", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserSignupPassword" },
                        label_html: { class: "modal-label" } %>
          </div>
        </div>
        <div class="col-lg-6 col-sm-12 pr-5">
          <div class="form-inputs">
            <%= f.input :password_confirmation,
                        label: "CONFIRM PASSWORD",
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        placeholder: "type password again...",
                        input_html: { autocomplete: "new-password", class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", id: "newUserSignupPasswordConfirm" },
                        label_html: { class: "modal-label" } %>


          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 col-sm-12 pr-5">
          <div class="form-inputs">

            <%= f.input :bio,
                        as: :text,
                        label: "BIO",
                        required: false,
                        placeholder: "write a bio...",
                        input_html: { class: "modal-input", style: "background: none; border: 0; border-bottom: 1px solid white;", rows: 1 },
                        label_html: { class: "modal-label" } %>
          </div>
        </div>

        <div class="col-lg-6 col-sm-12 pr-5">
          <div class="form-inputs">
            <%= f.input :photo,
                        as: :file,
                        label: "UPLOAD PROFILE PHOTO",
                        required: false,
                        placeholder: "give yourself a bio...",
                        input_html: { class: "modal-label login-submit", style: "background: none; border: 0;" },
                        label_html: { class: "modal-label" } %>

          </div>
          <div class="form-actions">
            <div class="d-flex justify-content-end">
              <div class="signUpErrors modal-label" style="color: red;"></div>
              <%= f.submit "SUBMIT", inner_text: "SUBMIT", style: "float: right; background: none; border: 0;", class: "modal-label login-submit" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container" style="display: none;">
        <div class="d-flex flex-column align-items-center" style="margin-top: 24px; width: 100%;">
          <%- if devise_mapping.omniauthable? %>
              <div>
                <h3 class="modal-label border-top border-dark" style="margin-bottom: 36px; text-align: center; padding-top: 16px;">Or sign up with socials:</h2>
              </div>

              <div class="d-flex justify-content-center pb-5 border-bottom border-dark">
                <%- resource_class.omniauth_providers.each do |provider| %>
                  <% if provider == :facebook %>
                    <%= link_to "", omniauth_authorize_path(resource_name, provider), class: "fab fa-facebook-f fa-3x fa-logo" %>
                    <div style="width:144px;"></div>
                  <% elsif provider == :github %>
                    <%= link_to "", omniauth_authorize_path(resource_name, provider), class: "fab fa-github fa-3x fa-logo" %>
                  <% end %>
                <% end %>
              </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_space_modal_card.html.erb
<div style="width:100%; height:100%;">
    <% card_image = image_path image %>
    <div class="choose_space_card" style="width:100%; height:100%; background-image: url(<%= card_image %>)">
      <div class="d-flex align-items-center">
        <%=  space.radio_button() %>
      </div>
    </div>
</div>

app/views/shared/_space_show_artwork_card.html.erb
<div class="artwork-card d-flex">
    <div class="artwork-card-art-panel">
      <% photo = "" %>
      <% if artwork.photo.attached? %>
        <% photo = artwork.photo %>
      <% elsif artwork.fast_photo.attached? %>
        <% photo = artwork.fast_photo %>
      <% end %>
      <% if artwork.artwork_type == "3D Model" %>
        <model-viewer src="<%= artwork.getArtworkURL %>" alt="Muse 3D model asset - id <%=artwork.id%>" auto-rotate camera-controls auto-rotate-delay="0" style="height: 100%; width: 100%;" ></model-viewer>
        <%#=  image_tag(photo.service_url, fetch_format: "png", width: "300px", background: "transparent", style: "height: 100%; width: 100%; object-fit: cover;") %>
      <% elsif artwork.artwork_type == "Image" %>

          <%= image_tag(artwork.getArtworkURL, width: "300px", style: "height: 100%; width: 100%; object-fit: cover;") %>

      <% elsif artwork.artwork_type == "Video" %>
        <div>
          <%= video_tag(artwork.getArtworkURL, width: "300px", controls: true, style: "height: 100%; width: 100%; object-fit: contain;") %>
        </div>
      <% elsif artwork.artwork_type == "Audio" %>
        <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

        <!-- WILL NEED TO ADD AN IMAGE OF THE AUDIO FILE'S SOUNDWAVE - SEE IF THERE IS A GEM FOR THIS?? -->
        <div style="height:500; position: relative;">
            <%#= image_tag(photo.service_url, width: "300px", height: "200px",flags: "waveform", resource_type: "video", color: "black", background: "transparent", controls: true, style: "width: 100%; margin-top: 50%; transform: translate(0, -50%);") %>
            <div style="height:500; position: absolute; top: 50%;">
              <%= video_tag(artwork.getArtworkURL, width: "300px", height: "50px", controls: true, style:"height: 100%; width: 100%; object-fit: contain;") %>
            </div>
        </div>



      <% end %>
    </div>
    <div class="artwork-card-info-panel d-flex flex-column justify-content-between">
      <div>
        <div>
          <h4 class="artwork-titles">NAME:</h4>
          <h4 class="artwork-info"><%=artwork.name%></h4><br>
        </div>
        <div>
          <h4 class="artwork-titles">DESCRIPTION:</h4>
          <h4 class="artwork-info"><%=artwork.description%></h4><br>
        </div>
        <div>
          <h4 class="artwork-titles">FILETYPE:</h4>
          <h4 class="artwork-info"><%=artwork.artwork_type%></h4><br>
        </div>
      </div>
      <div class="w-100">
        <button type="button" class="artwork-titles artwork-button transparent py-1 px-2" data-toggle="modal" data-target="#editArtwork<%=artwork.id%>Modal" data-backdrop="false">EDIT</button>
      </div>
    </div>
</div>

<div class="modal fade" style="backdrop-filter: blur(20px);z-index:6;" id="editArtwork<%=artwork.id%>Modal" tabindex="-1" role="dialog" aria-labelledby="editArtwork<%=artwork.id%>ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgba(255,255,255,0.93); border-radius: 8px;">
      <div class="modal-body pt-4">
        <div class="modal-header">
          <h5 class="modal-title" id="editArtwork<%=artwork.id%>ModalLabel">Edit artwork</h5>
          <button type="button" class="close" style="z-index:1;" data-dismiss="modal" data-target="#editArtwork<%=artwork.id%>Modal" aria-label="Close">
            <span aria-hidden="true">X</span>
          </button>
        </div>
        <%= (render partial: "edit_artwork", locals: { artwork: artwork }) %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_space_show_cover_photo.html.erb
<div class="main" >
    <% if space.photo.attached? %>
      <% image = image_path space.photo.service_url%>
    <% else %>
      <% image = image_path "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1418&q=80" %>
    <% end %>
    <div style="background-image: url(<%=image%>)" class="cardMain"></div>
</div>