config/routes.rb
Rails.application.routes.draw do
  get 'artworks_in_space/create'
  get 'artworks_in_space/destroy'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces do
    resources :artworks, only: [:create, :update]

    get 'vr', to: 'spaces#vr'
  end

  resources :user_space_templates, only: [:create, :destroy, :edit, :update]

  resources :artworks, only: :destroy
  resources :users, only: [:show, :index]

end

app/views/pages/_about.html.erb
<div id="about-modal-view" style="">
  <div class="container">

    <h2 class="login-title-label" style="padding-bottom: 24px;">About</h2>
    <p>Musei is a platform in its young days, here to bring fine art to those looking for it.
      <br><br> As an artist or curator, or simply if you’re curious, you can use Musei to create your own custom-made virtual reality exhibition. Musei accepts images, audio, video, and even 3D models to accommodate for your creations which exist outside of the digital realm.
      <br><br> If you head to Create Your Own, you can choose from a series of gallery templates with which to begin experimenting with your first virtual reality exhibit - you will find some options for classic galleries. However, we also believe that, with the advent of virtual reality, creatives can begin to explore new and striking places for their exhibitions - imagine being in outer space, or in an ancient temple - and so have provided some unusual gallery templates as well.
      <br><br> After selecting a gallery and naming it, you will be taken to a new screen to begin uploading your art. Try uploading a high quality image of a painting you made or of your favorite photograph, and select the type “image”.
      <br><br> Finally, with your first artwork uploaded into the gallery, you can select Launch Gallery, and you will immediately be taken into your personal virtual reality exhibition. In front of you, you should see your artwork, automatically inserted into a frame. Try dragging and dropping it with your mouse exactly where you want it in the space, and resizing it using the pop-up menu.
      <br><br> Now anybody can see your gallery when browsing Musei, and you can share the URL to invite anybody you want into your exhibit.
      <br><br> The gallery can be experienced just on your desktop like a videogame, on your smartphone, and even in virtual reality. If you don’t have a VR headset, you can find an inexpensive cardboard viewer, such as the Google Cardboard, and turn your smartphone into a VR headset.
      <br><br> We would really love to see Musei flourish into a platform that creatives can truly build the spaces that their art was meant to be in, and a place where art lovers and curious minds can get lost in wild worlds of art.
      <br><br> We are building a variety of tools to make the process more exciting and customizable.
      <br><br> We will also be implementing tools that can help artists turn their art into a living, from introducing them to interested art collectors, to providing services that will allow artists to create their own merchandise and memorabilia.
      <br><br> Of course, without your help, this platform will never take off. Which is why we would love to hear from you if you have any opinions about the site, ideas for features, questions, or even if you just want to say hi and get to know us a bit better.
    </p>
  </div>
</div>

app/views/pages/about.html.erb
 <div class="container page-padding">

    <h2 class="login-title-label" style="padding-bottom: 24px;">About</h2>
    <p>Musei is a platform in its young days, here to bring fine art to those looking for it.
      <br><br> As an artist or curator, or simply if you’re curious, you can use Musei to create your own custom-made virtual reality exhibition. Musei accepts images, audio, video, and even 3D models to accommodate for your creations which exist outside of the digital realm.
      <br><br> If you head to Create Your Own, you can choose from a series of gallery templates with which to begin experimenting with your first virtual reality exhibit - you will find some options for classic galleries. However, we also believe that, with the advent of virtual reality, creatives can begin to explore new and striking places for their exhibitions - imagine being in outer space, or in an ancient temple - and so have provided some unusual gallery templates as well.
      <br><br> After selecting a gallery and naming it, you will be taken to a new screen to begin uploading your art. Try uploading a high quality image of a painting you made or of your favorite photograph, and select the type “image”.
      <br><br> Finally, with your first artwork uploaded into the gallery, you can select Launch Gallery, and you will immediately be taken into your personal virtual reality exhibition. In front of you, you should see your artwork, automatically inserted into a frame. Try dragging and dropping it with your mouse exactly where you want it in the space, and resizing it using the pop-up menu.
      <br><br> Now anybody can see your gallery when browsing Musei, and you can share the URL to invite anybody you want into your exhibit.
      <br><br> The gallery can be experienced just on your desktop like a videogame, on your smartphone, and even in virtual reality. If you don’t have a VR headset, you can find an inexpensive cardboard viewer, such as the Google Cardboard, and turn your smartphone into a VR headset.
      <br><br> We would really love to see Musei flourish into a platform that creatives can truly build the spaces that their art was meant to be in, and a place where art lovers and curious minds can get lost in wild worlds of art.
      <br><br> We are building a variety of tools to make the process more exciting and customizable.
      <br><br> We will also be implementing tools that can help artists turn their art into a living, from introducing them to interested art collectors, to providing services that will allow artists to create their own merchandise and memorabilia.
      <br><br> Of course, without your help, this platform will never take off. Which is why we would love to hear from you if you have any opinions about the site, ideas for features, questions, or even if you just want to say hi and get to know us a bit better.
    </p>
  </div>

app/views/pages/home.html.erb
<% @title="Musei - Art in Virtual Reality - Homepage" %>

<div class="d-flex" id="landing-flex-box">
  <div id="landing-panel-left">

    <div class="d-flex flex-column justify-content-end main-page-button-list">
      <div></div>

      <div>
        <ul style="list-style-type: none; padding: 0 0 8px 0; margin: 0;">
          <li class="landing-list"><%= link_to "About", about_path %></li>
          <li class="landing-list"><%= link_to 'View Galleries', spaces_path %></li>
          <li class="landing-list"><%= link_to 'View Artists', users_path %></li>
          <% if user_signed_in? %>
            <li class="landing-list"><%= link_to 'Make your own', new_space_path %></li>
          <% else %>
             <li class="landing-list"> <%= link_to "Sign up and make your own", "#", id: "signup-modal-trigger" , class: "", data: {toggle: "modal", target: "#loginModal", backdrop: false} %></li>
          <% end %>
        </ul>
      </div>

      <div class="main-page-logo">
        <div>
          <span id="biglogo">MUSEI</span>
          <!-- <span id="biglogovr">.io</span> -->
          <span id="biglogoart" class="ml-2">.io</span>
        </div>
      </div>

    </div>

  </div>

  <div id="landing-image-strip" style="background-image: url(<%= image_path('gallery.jpg') %>);">

  </div>

  <div id="landing-panel-right" style="position: relative;">
    <span id="featured-artist">Featured Artist: Jemima Jackson</span>

  </div>
</div>